# TYPE WALLET MODE
TYPE_WALLET = "argent"  # argent/braavos

# RANDOM WALLETS MODE
RANDOM_WALLET = True  # True/False

# removing a wallet from the list after the job is done
REMOVE_WALLET = True

SLEEP_FROM = 60
SLEEP_TO = 600

QUANTITY_THREADS = 1

THREAD_SLEEP_FROM = 150
THREAD_SLEEP_TO = 450

# GWEI CONTROL MODE
CHECK_GWEI = True
MAX_GWEI = 38

# RETRY MODE
RETRY_COUNT = 1

# CAIRO VERSION CONTROL
CAIRO_VERSION = 1

FEE_MULTIPLIER = 1.5
